version: '3.8'
services:
  game:
    container_name: game
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - shared
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=secret
      - JWT_SALT=salt
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: khalidmagnificent
      POSTGRES_PASSWORD: 190204
      POSTGRES_DB: game
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - shared
    ports:
      - 12345:5432

networks:
  shared:
    driver: bridge
volumes:
  db_data:
