version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: khalidmagnificent
      POSTGRES_PASSWORD: 190204
      POSTGRES_DB: game
    ports:
      - 12345:5432
  game:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=secret
      - JWT_SALT=salt
    depends_on:
      - db